<Project Sdk="MSTest.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Sources\Blog\Blog.csproj" />
    <ProjectReference Include="..\..\Sources\Testing\Testing.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>

</Project>
